trigger:
  branches:
    include:
      - main
variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  dotNetVersion: '8.0.x'
stages:
- stage: Build
  jobs:
  - job: BuildJob
    pool:
      vmImage: 'windows-latest'
    steps:
    - task: UseDotNet@2
      inputs:
        version: $(dotNetVersion)
        includePreviewVersions: false
    - task: DotNetCoreCLI@2
      displayName: 'Restore NuGet packages'
      inputs:
        command: 'restore'
        projects: '$(solution)'
    - task: DotNetCoreCLI@2
      displayName: 'Build solution'
      inputs:
        command: 'build'
        projects: '$(solution)'
        arguments: '--configuration $(buildConfiguration) --no-restore'
    - task: DotNetCoreCLI@2
      displayName: 'Run unit tests'
      inputs:
        command: 'test'
        projects: '**/*Tests/*.csproj'
        arguments: '--configuration $(buildConfiguration) --no-build'
    - task: DotNetCoreCLI@2
      displayName: 'Publish Web API'
      inputs:
        command: 'publish'
        publishWebProjects: true
        arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
        zipAfterPublish: true
    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact'
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'webapi'
        publishLocation: 'Container'
- stage: DeployToTest
  dependsOn: Build
  condition: succeeded()
  jobs:
  - deployment: DeployTest
    environment: 'test'
    pool:
      vmImage: 'windows-latest'
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: 'webapi'
          
          - task: AzureKeyVault@2
            displayName: 'Azure Key Vault - Test'
            inputs:
              azureSubscription: 'Gift-KeyVault'
              KeyVaultName: 'test-key-vault-v2'
              RunAsPreJob: false

          - task: AzureWebApp@1
            inputs:
              azureSubscription: 'Gift'
              appName: 'test-gift-api-rpr'
              package: '$(Pipeline.Workspace)/webapi/*.zip'
              deploymentMethod: 'auto'
              appSettings: |
                -ConnectionStrings__DefaultConnection "@Microsoft.KeyVault(SecretUri=https://test-key-vault-v2.vault.azure.net/secrets/GiftApi--DefaultConnection)"
                -NotificationSettings__SendGridApiKey "@Microsoft.KeyVault(SecretUri=https://test-key-vault-v2.vault.azure.net/secrets/GiftApi--SendGridApiKey)"
                -NotificationSettings__SendGridFromEmail "@Microsoft.KeyVault(SecretUri=https://test-key-vault-v2.vault.azure.net/secrets/GiftApi--SendGridFromEmail)"
                -NotificationSettings__SendGridFromName "@Microsoft.KeyVault(SecretUri=https://test-key-vault-v2.vault.azure.net/secrets/GiftApi--SendGridFromName)"
                -Jwt__Key "@Microsoft.KeyVault(SecretUri=https://test-key-vault-v2.vault.azure.net/secrets/GiftApi--JwtKey)"
                
- stage: DeployToProd
  dependsOn: DeployToTest
  condition: succeeded()
  jobs:
  - deployment: DeployProd
    environment: 'production'
    pool:
      vmImage: 'windows-latest'
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: 'webapi'
          
          - task: AzureKeyVault@2
            displayName: 'Azure Key Vault - Production'
            inputs:
              azureSubscription: 'Gift-KeyVault'
              KeyVaultName: 'prod-key-vault-v1'
              RunAsPreJob: false

          - task: AzureWebApp@1
            inputs:
              azureSubscription: 'Gift'
              appName: 'prod-gift-api-rpr'
              package: '$(Pipeline.Workspace)/webapi/*.zip'
              deploymentMethod: 'auto'
              appSettings: |
                -ConnectionStrings__DefaultConnection "@Microsoft.KeyVault(SecretUri=https://prod-key-vault-v1.vault.azure.net/secrets/GiftApi--DefaultConnection)"
                -NotificationSettings__SendGridApiKey "@Microsoft.KeyVault(SecretUri=https://prod-key-vault-v1.vault.azure.net/secrets/GiftApi--SendGridApiKey)"
                -NotificationSettings__SendGridFromEmail "@Microsoft.KeyVault(SecretUri=https://prod-key-vault-v1.vault.azure.net/secrets/GiftApi--SendGridFromEmail)"
                -NotificationSettings__SendGridFromName "@Microsoft.KeyVault(SecretUri=https://prod-key-vault-v1.vault.azure.net/secrets/GiftApi--SendGridFromName)"
                -Jwt__Key "@Microsoft.KeyVault(SecretUri=https://prod-key-vault-v1.vault.azure.net/secrets/GiftApi--JwtKey)"